# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: python

os: linux
dist: trusty
group: edge

python:
  - "2.7.12"

perl:
  - "5.24"

addons:
  apt:
    packages:
      - libspatialindex-dev
      - bedtools

env:
    matrix:
        - TESTENV=docs
        - TESTENV=code
        - TESTENV=pylint

#create folders for installation
before_install:
    - sudo apt-get install gawk
    - chmod +x ./tests/run_tests.sh
    - mkdir -p ${HOME}/bin
    - mkdir -p ${HOME}/lib
    - export PATH="${HOME}/bin:$PATH"
    - cd ${HOME}/lib

    # install hicup
    - wget https://www.bioinformatics.babraham.ac.uk/projects/hicup/hicup_v0.6.1.tar.gz
    - tar -xzf hicup_v0.6.1.tar.gz
    - cd hicup_v0.6.1
    - chmod a+x *

    # install bwa
    - cd ${HOME}/lib
    - wget https://sourceforge.net/projects/bio-bwa/files/bwa-0.7.17.tar.bz2
    - bzip2 -d bwa-0.7.17.tar.bz2
    - tar -xf bwa-0.7.17.tar
    - cd bwa-0.7.17
    - make

    # install bowtie2
    - cd ${HOME}/lib
    - wget --max-redirect 1 https://downloads.sourceforge.net/project/bowtie-bio/bowtie2/2.3.4/bowtie2-2.3.4-linux-x86_64.zip
    - unzip bowtie2-2.3.4-linux-x86_64.zip

    #install htslib
    - cd ${HOME}/lib
    - git clone https://github.com/samtools/htslib.git
    - cd htslib
    - autoheader
    - autoconf
    - ./configure --prefix=${HOME}/lib/htslib
    - make
    - make install

    # install samtools
    - cd ${HOME}/lib
    - git clone https://github.com/samtools/samtools.git
    - cd samtools
    - autoheader
    - autoconf -Wno-syntax
    - ./configure --prefix=${HOME}/lib/samtools
    - make
    - make install

    #latest version of R
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
    - echo "deb http://cran.r-project.org/bin/linux/ubuntu trusty/" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install r-base-core
    - sudo apt-get install python-rpy2

    #Get chicago preprocessing scripts
    - cd ${HOME}/build/Multiscale-Genomics/CHi-C/CHiC/tool/scripts/
    - wget https://bitbucket.org/chicagoTeam/chicago/raw/e288015f75d36c5367d1595e0ac8099f2ce82aa1/chicagoTools/runChicago.R
    - wget https://bitbucket.org/chicagoTeam/chicago/raw/e288015f75d36c5367d1595e0ac8099f2ce82aa1/chicagoTools/bam2chicago.sh
    - wget https://bitbucket.org/chicagoTeam/chicago/raw/e288015f75d36c5367d1595e0ac8099f2ce82aa1/chicagoTools/makeDesignFiles.py
    - chmod +x bam2chicago.sh

    #installing chicago
    -  sudo apt-get install libtbb-dev
    -  sudo apt-get install libssl-dev
    -  cd ${HOME}/build/Multiscale-Genomics/CHi-C/
    - sudo chmod +x CHiC/tool/scripts/travis/docs_harness.sh
    - sudo chmod +x CHiC/tool/scripts/travis/pylint_harness.sh
    - sudo Rscript CHiC/tool/scripts/install_packages.R

    - cd ${HOME}/build/Multiscale-Genomics/CHi-C/

# command to install dependencies
install:
    - pip install --upgrade setuptools pip
    - pip install --upgrade -e .
    - pip install -r requirements.txt
    - if [[ "$TESTENV" == "docs" ]]; then pip install sphinx;fi
    - if [[ "$TESTENV" == "pylint" ]]; then pip install pylint;fi

before_script:
    - cd ${HOME}/bin

    - ln -s ${HOME}/lib/bedtools2/bin/* .

    - ln -s ${HOME}/lib/hicup_v0.6.1/* ${HOME}/bin/

    - ln -s ${HOME}/lib/bwa-0.7.17/bwa ${HOME}/bin/

    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2
    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2-align-l
    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2-align-l-debug
    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2-align-s
    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2-align-s-debug
    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2-build
    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2-build-l
    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2-build-l-debug
    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2-build-s
    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2-build-s-debug
    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2-inspect
    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2-inspect-l
    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2-inspect-l-debug
    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2-inspect-s
    - ln -s ${HOME}/lib/bowtie2-2.3.4-linux-x86_64/bowtie2-inspect-s-debug

    - ln -s ${HOME}/lib/htslib/bin/bgzip bgzip
    - ln -s ${HOME}/lib/htslib/bin/htsfile htsfile
    - ln -s ${HOME}/lib/htslib/bin/tabix tabix

    - ln -s ${HOME}/lib/samtools/bin/ace2sam ace2sam
    - ln -s ${HOME}/lib/samtools/bin/blast2sam.pl blast2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/bowtie2sam.pl bowtie2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/export2sam.pl export2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/interpolate_sam.pl interpolate_sam.pl
    - ln -s ${HOME}/lib/samtools/bin/maq2sam-long maq2sam-long
    - ln -s ${HOME}/lib/samtools/bin/maq2sam-short maq2sam-short
    - ln -s ${HOME}/lib/samtools/bin/md5fa md5fa
    - ln -s ${HOME}/lib/samtools/bin/md5sum-lite md5sum-lite
    - ln -s ${HOME}/lib/samtools/bin/novo2sam.pl novo2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/plot-bamstats plot-bamstats
    - ln -s ${HOME}/lib/samtools/bin/psl2sam.pl psl2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/sam2vcf.pl sam2vcf.pl
    - ln -s ${HOME}/lib/samtools/bin/samtools samtools
    - ln -s ${HOME}/lib/samtools/bin/samtools.pl samtools.pl
    - ln -s ${HOME}/lib/samtools/bin/seq_cache_populate.pl seq_cache_populate.pl
    - ln -s ${HOME}/lib/samtools/bin/soap2sam.pl soap2sam.pl
    - ln -s ${HOME}/lib/samtools/bin/varfilter.py varfilter.py
    - ln -s ${HOME}/lib/samtools/bin/wgsim wgsim
    - ln -s ${HOME}/lib/samtools/bin/wgsim_eval.pl wgsim_eval.pl
    - ln -s ${HOME}/lib/samtools/bin/zoom2sam.pl zoom2sam.pl

# command to run tests
script:
    - cd ${HOME}/build/Multiscale-Genomics/CHi-C
    - if [[ "$TESTENV" == "code" ]]; then python tests/test_toolchains.py
    - if [[ "$TESTENV" == "docs" ]]; then CHiC/tool/scripts/travis/docs_harness.sh; fi
    - if [[ "$TESTENV" == "pylint" ]]; then CHiC/tool/scripts/travis/pylint_harness.sh; fi

